todays_events_keyword: 'tdy'
tomorrows_events_keyword: 'tmr'
weather_keyword: 'w'
email_keyword: 'e'
email_to: 'felipealamos@gmail.com'
email_sender: 'felipealamos@gmail.com '
calendars_ids: ['primary', 'ims45u9bmo1rse8skeb865pdjg@group.calendar.google.com']